spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/community_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq2826053
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static

server:
  port: 9000
  servlet:
    context-path: /user

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cms.user.entity

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
