spring:
  application:
    name: api-gateway

server:
  port: 4000


zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://127.0.0.1:6001
      stripPrefix: false
      sensitiveHeaders:

