spring:
  application:
    name: community-service
  datasource:
    url: jdbc:mysql://localhost:3306/community_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq2826053
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9001
  servlet:
    context-path: /community

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cms.common


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true

#配置分页插件pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.cms.auth.dao: debug