spring:
  application:
    name: community-service
  datasource:
    url: jdbc:mysql://localhost:3306/community_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq2826053
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9002
  servlet:
    context-path: /community

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cms.common.entity


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true