spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/community_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qq2826053
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static


server:
  port: 6001
  servlet:
    context-path: /uaa

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.cms.auth.entity

logging:
  level:
    com.cms.auth.dao: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
