server:
  port: 10000
  servlet:
    context-path: /web
    session:
      cookie:
        name: UISESSION


spring:
  application:
    name: web-api

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true


community-service:
  ribbon:
    listOfServers: http://127.0.0.1:9001



