server:
  port: 8888
spring:
  application:
    name: manager-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared/
  security:
    user:
      name: config
      password: configpwd

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
